language: ruby
bundler_args: --without development
before_script:
  - "bundle exec rake refinery:solr:dummy_app"

rvm:
  - 1.9.3
  - 2.0.0
env:
  - "RAILS_VERSION=4.0.0"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: true

script: "bundle exec rake spec"